### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lucianomlima**
# Summary

Add instructions to init a new app with legacy cli installed

## Checklist

- [ ] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by radko93** [comment]
I'm not sure if I want to merge this, we should really make people use new CLI to make everyone's life easier. Is there any reason to keep old CLI? The new one also works with RN 0.61.

**Comment by lucianomlima** [comment]
> I'm not sure if I want to merge this, we should really make people use new CLI to make everyone's life easier. Is there any reason to keep old CLI? The new one also works with RN 0.61.

Here we have some apps that are in the 0.59 version yet. And all the time I forget to pass `--ignore-existing`. 😅
Upgrading RN it's not so easy yet and this tip can become useful.
But I understand your reasons. It's up to you to merge or close it.

**Comment by emin93** [comment]
I would argue that this is not related to the template but to the RN CLI. Therefore I‘d rather do a PR in the RN repo.

**Comment by lucianomlima** [comment]
> I would argue that this is not related to the template but to the RN CLI. Therefore I‘d rather do a PR in the RN repo.

Yeah, is related to npx and how it manage deps when It found it in the global local scope.

In these cases, people can get some problems because don't know that the local library will be used in the process.

Can lead to come here tô open a issue that it's not related do template. With this tip, Maybe can vê avoided.

**Pull request closed without merging**
