### PR TITLE
Fix suggested usage for RN >= 0.60

### LINKED ISSUE #57: error Error: Cannot find module '/var/folders/2y/.../T/rncli-init-template-jUussB/node_modules/typescript/template.config'
# Question

When trying to init a new project I get the following error message:
```
~/MyDev/test$ npx react-native init myapp --template typescript
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn Once Write Anywhere                

✔ Downloading template
✖ Copying template
error Error: Cannot find module '/var/folders/2y/kvrr5nws6xz4nx9vnwjxj17w0000gn/T/rncli-init-template-jUussB/node_modules/typescript/template.config'
Require stack:
- /Users/doberkofler/.npm/_npx/27475/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/template.js
- /Users/doberkofler/.npm/_npx/27475/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/init.js
- /Users/doberkofler/.npm/_npx/27475/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/init/index.js
- /Users/doberkofler/.npm/_npx/27475/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/doberkofler/.npm/_npx/27475/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/cliEntry.js
- /Users/doberkofler/.npm/_npx/27475/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js
- /Users/doberkofler/.npm/_npx/27475/lib/node_modules/react-native/cli.js
```

### PR DESCRIPTION
**Pull request by radko93**
# Summary
The default Readme displayed on github does not show the recommended way to use this template with RN >= 0.60.

fixes #57

### CODE REVIEW

**Comment by taoliujun** [comment]
thx, i used new command and it done well.

**Comment by vanlethi** [comment]
I had the same problem but when I used '[npx Reac -igen init MyApp --template Reac -igen-template-typescript @ next] (url)' it didn't work. Do you have another way?

**Comment by radko93** [comment]
I don't know what `-igen` means @vanlethi

**Comment by ZhengKehang** [comment]
I used the new CLI `npx react-native init MyApp --template react-native-template-typescript@next` and uninstall react-native-cli,but still have this problem

**Pull request merged**
