### PR TITLE
Fix file mode and whitespace errors

### PR DESCRIPTION
**Pull request by friederbluemle**
A bunch of non-executable files in the repo erroneously had the executable bit set. This fixes it by changing the file mode from `755` to `644`.

It also fixes all whitespace errors in this repo - e.g. missing newline at EOF, trailing whitespace.

### CODE REVIEW

**Comment by emin93** [comment]
The RN TypeScript template is based on the default RN template (https://github.com/facebook/react-native/tree/v0.61.5/template) and aims to be as consistent as possible with it. It seems that the issue persists there as well, so I'd suggest you to create a PR in the RN repo and then we merge it over here.

**Comment by friederbluemle** [comment]
Thanks for your reply @emin93 - The main React Native template does not contain trailing whitespace errors (or incorrectly set file modes). If you think otherwise, can you please point me to the specific files you're referring to? Thank you!

**Comment by emin93** [comment]
Welp, I relied too much on the GitHub editor/viewer which seems to not render EOF newlines 😅. I just downloaded the default template and realized they do indeed have EOF newlines. Therefore I apologize.

**Comment by friederbluemle** [comment]
Haha, no worries, thanks @emin93 :+1:
Have a nice weekend!

**Pull request merged**
