### PR TITLE
feat: update react-native to 0.63.2 and @types/react-native to 0.63.2

### PR DESCRIPTION
**Pull request by abakimatov**
# Summary

Update versions of react-native and @types/react-native to 0.63.2 version

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by emin93** [comment]
Upgrading from 0.63.0 to 0.63.2 requires some changes in the gradle and Xcode project. Can you include those changes as well? (https://react-native-community.github.io/upgrade-helper/?from=0.63.0&to=0.63.2)

You can merge the changes over from here e.g. by copying over the android & iOS folder: https://github.com/facebook/react-native/tree/v0.63.2/template

**Comment by abakimatov** [comment]
Oh my bad. Ofc, i can :)

**Comment by abakimatov** [comment]
Guys, i also added `.idea` config directory to gitignore,  because this directory was added to my commit. I hope this won't be a problem. Sorry for a little messy pull request. )

**Comment by radko93** [comment]
@abakimatov if you added it but it was not there before please remove it

**Comment by emin93** [comment]
This has way too many changes, should have only 3 changed files in total (`package.json`, `android/app/build.gradle` and `ios/RnDiffApp.xcodeproj/project.pbxproj`). Are you sure you didn't modify anything after copying over the latest template?

**Comment by abakimatov** [comment]
> @abakimatov if you added it but it was not there before please remove it

i removed it in the last commit, but if you want,

**Comment by abakimatov** [comment]
Okay guys, my bad, sorry, now i was just copied `build.gradle` and `project.pbxproj` from original latest template here. Also `.idea` directory was be added to .gitignore. And i was clear commits history.

**Comment by radko93** [comment]
If you look at this https://react-native-community.github.io/upgrade-helper/?from=0.63.0&to=0.63.2 there's no `.idea` file added

**Comment by abakimatov** [comment]
> If you look at this https://react-native-community.github.io/upgrade-helper/?from=0.63.0&to=0.63.2 there's no `.idea` file added

okay, i removed it

**Pull request merged**
