### PR TITLE
Extend recommended React Native TSConfig base

### PR DESCRIPTION
**Pull request by leotm**
Context

- https://github.com/tsconfig/bases/pull/116

To keep our recommended React Native TSConfig base as the source

---

`yarn set version classic`

- [x] Add devdep
- [x] Extend
- [x] Doc
- [x] Remove `ts --init` comment boilerplate (can still remove further)
- [x] Remove `es2019` override
- [x] Remove `forceConsistentCasingInFileNames` override

_Have a think if [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) should be recommended for React Native, we do in [few others](https://github.com/tsconfig/bases/search?q=skipLibCheck)_

<s>Remove duplicate rule overrides</s>
<s>Keep duplicate rule overrides for visibility</s>

### CODE REVIEW

**Comment by leotm** [comment]
sure ^ how do you feel about what @orta mentioned btw

**Comment by leotm** [comment]
i'm also considering if it's ideal for each

Screenshot 2022-06-30 at 12 38 52

**Comment by orta** [comment]
Yeah, IMO, you should present an empty tsconfig if you're going with the `extends`

**Comment by leotm** [comment]
done ^ much more minimal

Screenshot 2022-06-30 at 16 11 20

happy to remove the rest of the comments still if we want near-fully empty tsconfig

**Comment by leotm** [comment]
and happy to remove any overrides like es2019 once merged in
https://github.com/tsconfig/bases/blob/main/bases/react-native.json

**Review by radko93 — APPROVED** [review]

**Comment by radko93** [comment]
LGTM, great work!

**Pull request merged**
