### PR TITLE
Update lib

### PR DESCRIPTION
**Pull request by Hatko**
# Summary

As discussed [here](https://github.com/react-native-community/react-native-template-typescript/issues/136), it makes sense to have lib consistent with the target. 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

### CODE REVIEW

**Comment by LinusU** [comment]
Hmm, this will probably add new APIs that aren't yet present on React Native though 🤔 

e.g. it would make definitions for `BigInt` available, but React Native doesn't support that: https://github.com/facebook/react-native/issues/28492

**Comment by LinusU** [comment]
added a more thorough explanation in the issue:

> The reason why target and lib is set to different is because Metro will use Babel to transpile the _syntax_, which is what `target` controls.
> 
> On the other hand, `lib` specifies which part of the standard library exists, which isn't handled by Babel.
> 
> e.g. `"syntax": "esnext"` will allow you to use `async function` and `await`, which Babel can transpile. On the other hand, `"lib": "esnext"` will allow you to use `BigInt`, which will then fail at runtime because `BigInt` isn't supported...

**Comment by Hatko** [comment]
@LinusU Interesting. Do you know if there is an official source where you can check the list of available/not available features? Or the rule of a thumb is not to use `esnext` at all?

**Comment by LinusU** [comment]
@Hatko unfortunately not, I need to do some more investigation on this, but I believe that from React Native 0.63 (soon to be released) your code will either run on the engine from Safari 10, the bundled engine on Android, or Hermes.

With that information we should be able to figure out the correct target by using the Kangax tables: http://kangax.github.io/compat-table/es6/

> Or the rule of a thumb is not to use `esnext` at all?

I would advice against using `esnext` since it will automatically opt you in to any new features without knowing if they are compatible with your platform or not...

**Comment by LinusU** [comment]
e.g. `Promise#finally` is not included in list of polyfills, is defined in [`lib.es2018.promise`](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2018.promise.d.ts) but is not available on iOS <11.3. Thus, setting lib to `es2018` (or `esnext`) would allow people to write `.finally` on Promises, which would then fail at runtime.

**Comment by LinusU** [comment]
From an initial reading, it seems like library could potentially be updated to `ES2017` when targeting React Native 0.63 (only release candidate right now)

**Comment by Hatko** [comment]
@LinusU Perfect, thanks for a comprehensive answer.

**Pull request closed without merging**
